DEBUG:appServiceAppLogs:Waiting for the logs flag to be set
INFO:appsvc_profiler.installer:Code Profiler Installer is starting up
INFO:appsvc_profiler.installer:Cleaning up any existing status file which indicated signal handlers initialized status
INFO:appsvc_profiler.installer:Attempting to delete the signal_handler status file for instance id 723a5e2d371f6deba79eab8b7c111520c7ef9bd6c79c5131aeeacb774e89c15e
INFO:appsvc_profiler.installer:successfully deleted the status file
DEBUG:appsvc_profiler.installer:APPSETTING_WEBSITE_ENABLE_DEFAULT_CODE_PROFILER : None
INFO:appsvc_profiler.installer:Attempting to install the default code profiler.
DEBUG:appsvc_profiler.installer:viztracer would save traces to /tmp/723a5e_profiler_trace.json
INFO:appsvc_profiler.installer:Successfully installed code profiler.
INFO:appsvc_profiler.installer:Signal Handlers SIGUSR for needed code-profiler have been initialized for gunicorn process on instance 723a5e2d371f6deba79eab8b7c111520c7ef9bd6c79c5131aeeacb774e89c15e
DEBUG:appsvc_profiler.installer:Code Profiler Installer is exiting as installation is completed
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
ERROR:app:Exception on / [HEAD]
Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'predictui' did not return a valid response. The function either returned None or ended without a return statement.
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875105670528) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:d2ae27df-272e-4c78-b51b-274f5c521576. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:d2ae27df-272e-4c78-b51b-274f5c521576. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875105611056) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:d2ae27df-272e-4c78-b51b-274f5c521576> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:d2ae27df-272e-4c78-b51b-274f5c521576. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:d2ae27df-272e-4c78-b51b-274f5c521576'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction opening *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875105618864) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:6338a25d-1e53-4767-9479-1b463ada74f1'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.267446
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 4862
INFO:app:time_domain_expiration 251
INFO:app:qty_ip_resolved 3
INFO:app:qty_nameservers 4
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 3
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: accounts.datastax.com
INFO:app:URL: https://accounts.datastax.com/session-service
INFO:app:*****************Prediction for https://accounts.datastax.com/session-service is Prediction says phishing URL *************************
ERROR:cassandra.datastax.cloud:HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
ERROR:cassandra.datastax.cloud:HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
ERROR:app:Exception on /history [GET]
Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/tmp/8dc58abaef33584/app.py", line 76, in fetchui
    all_entries = fetch_all_entries()
  File "/tmp/8dc58abaef33584/connect_database.py", line 60, in fetch_all_entries
    cluster, session = connect_to_cassandra()
  File "/tmp/8dc58abaef33584/connect_database.py", line 24, in connect_to_cassandra
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
  File "cassandra/cluster.py", line 1172, in cassandra.cluster.Cluster.__init__
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 91, in get_cloud_config
    config = read_metadata_info(config, cloud_config)
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 140, in read_metadata_info
    raise DriverException("Unable to connect to the metadata service at %s. "
cassandra.DriverException: Unable to connect to the metadata service at https://74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29080/metadata. Check the cluster status in the cloud console. 
ERROR:cassandra.datastax.cloud:HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
ERROR:app:Exception on /history [GET]
Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 137, in read_metadata_info
    response = urlopen(url, context=config.ssl_context, timeout=timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/3.9.18/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/tmp/8dc58abaef33584/app.py", line 76, in fetchui
    all_entries = fetch_all_entries()
  File "/tmp/8dc58abaef33584/connect_database.py", line 60, in fetch_all_entries
    cluster, session = connect_to_cassandra()
  File "/tmp/8dc58abaef33584/connect_database.py", line 24, in connect_to_cassandra
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
  File "cassandra/cluster.py", line 1172, in cassandra.cluster.Cluster.__init__
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 91, in get_cloud_config
    config = read_metadata_info(config, cloud_config)
  File "/tmp/8dc58abaef33584/antenv/lib/python3.9/site-packages/cassandra/datastax/cloud/__init__.py", line 140, in read_metadata_info
    raise DriverException("Unable to connect to the metadata service at %s. "
cassandra.DriverException: Unable to connect to the metadata service at https://74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29080/metadata. Check the cluster status in the cloud console. 
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875001660128) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.087534
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 4862
INFO:app:time_domain_expiration 251
INFO:app:qty_ip_resolved 3
INFO:app:qty_nameservers 4
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 3
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: accounts.datastax.com
INFO:app:URL: https://accounts.datastax.com/session-service
INFO:app:*****************Prediction for https://accounts.datastax.com/session-service is Prediction says safe browsing URL *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875606074272) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.179482
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 4862
INFO:app:time_domain_expiration 251
INFO:app:qty_ip_resolved 3
INFO:app:qty_nameservers 4
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 1
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: accounts.datastax.com
INFO:app:URL: https://accounts.datastax.com/session-service
INFO:app:*****************Prediction for https://accounts.datastax.com/session-service is Prediction says phishing URL *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875605883920) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.071952
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 4862
INFO:app:time_domain_expiration 251
INFO:app:qty_ip_resolved 3
INFO:app:qty_nameservers 4
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 3
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: accounts.datastax.com
INFO:app:URL: https://accounts.datastax.com/session-service
INFO:app:*****************Prediction for https://accounts.datastax.com/session-service is Prediction says safe browsing URL *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875606163312) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.186839
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 4862
INFO:app:time_domain_expiration 251
INFO:app:qty_ip_resolved 3
INFO:app:qty_nameservers 4
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 3
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: accounts.datastax.com
INFO:app:URL: https://accounts.datastax.com/session-service
INFO:app:*****************Prediction for https://accounts.datastax.com/session-service is Prediction says phishing URL *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875094330432) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:4319ee3b-d670-4dd9-a515-d0386d3c7745. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:4319ee3b-d670-4dd9-a515-d0386d3c7745. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875103692880) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:4319ee3b-d670-4dd9-a515-d0386d3c7745> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:4319ee3b-d670-4dd9-a515-d0386d3c7745. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:4319ee3b-d670-4dd9-a515-d0386d3c7745'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.078938
INFO:app:domain_spf 0
INFO:app:asn_ip 1
INFO:app:time_domain_activation 9707
INFO:app:time_domain_expiration 1614
INFO:app:qty_ip_resolved 6
INFO:app:qty_nameservers None
INFO:app:qty_mx_servers None
INFO:app:ttl_hostname 1
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: www.google.com
INFO:app:URL: https://www.google.com/
INFO:app:*****************Prediction for https://www.google.com/ is Prediction says safe browsing URL *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875094466912) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:time_response 0.381101
INFO:app:domain_spf 1
INFO:app:asn_ip 1
INFO:app:time_domain_activation 3321
INFO:app:time_domain_expiration 1061
INFO:app:qty_ip_resolved 1
INFO:app:qty_nameservers 2
INFO:app:qty_mx_servers 1
INFO:app:ttl_hostname 6
INFO:app:tls_ssl_certificate 1
INFO:app:qty_redirects 0
INFO:app:url_google_index 1
INFO:app:domain_google_index 0
INFO:app:url_shortened 0
INFO:app:Domain: darebee.com
INFO:app:URL: https://darebee.com/collections/cardio-for-overweight-people-workouts.html
INFO:app:*****************Prediction for https://darebee.com/collections/cardio-for-overweight-people-workouts.html is Prediction says phishing URL *************************
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875001047360) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:e5c45364-786f-4686-9cfc-193c25d62a93'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
ERROR:cassandra.connection:Closing connection <LibevConnection(137875001045440) 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
INFO:cassandra.policies:Using datacenter 'us-east-1' for DCAwareRoundRobinPolicy (via host '74f3ea48-05df-4249-a12b-fac40645190d-us-east-1.db.astra.datastax.com:29042:277de8f5-b235-40ad-9731-52e3bad98dbe'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:*****************Prediction for URL started *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
INFO:app:*****************Prediction opening *************************
